from app.core.database import SessionLocal, engine, Base
from app.models.models import Artisan, Product, ProductMedia, ProductPricing, Order, Review
from datetime import datetime, timedelta

def seed_database():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    
    # If 16 products already exist, skip
    if db.query(Product).count() >= 16:
        db.close()
        return

    print("Seeding KALAKART database with 16 authentic GI-certified master crafts...")
    try:
        db.query(Order).delete()
        db.query(Review).delete()
        db.query(ProductPricing).delete()
        db.query(ProductMedia).delete()
        db.query(Product).delete()
        db.query(Artisan).delete()
        db.commit()
    except Exception as e:
        db.rollback()
        print("Note on cleanup:", e)

    artisans_data = [
        {
            "id": "artisan_rukmini",
            "name": "Rukmini Devi",
            "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80",
            "phone": "+91 98290 14820",
            "state": "Rajasthan",
            "cluster": "Jaipur Blue Pottery Guild",
            "craft_type": "Pottery & Ceramics",
            "scheme_id": "PM-VISH-RJ-1002",
            "bio": "Rukmini has been creating handpainted blue pottery pieces for over 15 years. Her work reflects the royal heritage of Jaipur.",
            "gi_tag": "GI-TAG-RJ-02 (Jaipur Blue Pottery)",
            "experience_years": 18,
            "total_sales": 42850.0,
            "active_listings": 18,
            "pending_orders": 7,
            "total_earnings": 28400.0
        },
        {
            "id": "artisan_ramprasad",
            "name": "Ramprasad Vishwakarma",
            "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
            "phone": "+91 94152 88201",
            "state": "Uttar Pradesh",
            "cluster": "Varanasi Handloom Weavers Collective",
            "craft_type": "Textiles & Weaving",
            "scheme_id": "PM-VISH-UP-0042",
            "bio": "5th-generation master weaver specializing in pure mulberry silk katan dupattas with hand-twisted gold zari borders.",
            "gi_tag": "GI-TAG-UP-01 (Banaras Brocades & Sarees)",
            "experience_years": 26,
            "total_sales": 78200.0,
            "active_listings": 14,
            "pending_orders": 5,
            "total_earnings": 52100.0
        },
        {
            "id": "artisan_meera",
            "name": "Meera Kumbhar",
            "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
            "phone": "+91 97230 45811",
            "state": "Uttar Pradesh",
            "cluster": "Khurja Terracotta Guild",
            "craft_type": "Pottery & Ceramics",
            "scheme_id": "PM-VISH-UP-0118",
            "bio": "Master potter creating wheel-thrown terracotta and glazed ceramics using traditional wood-fired kilns.",
            "gi_tag": "GI-TAG-UP-04 (Khurja Pottery)",
            "experience_years": 14,
            "total_sales": 31200.0,
            "active_listings": 12,
            "pending_orders": 4,
            "total_earnings": 21800.0
        },
        {
            "id": "artisan_aslam",
            "name": "Mohammad Aslam",
            "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
            "phone": "+91 98371 66520",
            "state": "Uttar Pradesh",
            "cluster": "Moradabad Brass Guild",
            "craft_type": "Metalwork & Brass",
            "scheme_id": "PM-VISH-UP-0294",
            "bio": "Hereditary brass artisan specializing in hand-chiseled decorative brassware and ceremonial diyas.",
            "gi_tag": "GI-TAG-UP-07 (Moradabad Metal Craft)",
            "experience_years": 22,
            "total_sales": 54600.0,
            "active_listings": 16,
            "pending_orders": 6,
            "total_earnings": 38200.0
        },
        {
            "id": "artisan_shanti",
            "name": "Shanti Devi",
            "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
            "phone": "+91 99312 40019",
            "state": "Bihar",
            "cluster": "Mithila Folk Painting Collective",
            "craft_type": "Paintings & Art",
            "scheme_id": "PM-VISH-BR-0083",
            "bio": "National award-winning Madhubani artist depicting nature, mythology, and village life using natural plant dyes.",
            "gi_tag": "GI-TAG-BR-01 (Madhubani Paintings)",
            "experience_years": 30,
            "total_sales": 89400.0,
            "active_listings": 20,
            "pending_orders": 9,
            "total_earnings": 68000.0
        },
        {
            "id": "artisan_imran",
            "name": "Imran Ansari",
            "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80",
            "phone": "+91 98970 33418",
            "state": "Uttar Pradesh",
            "cluster": "Saharanpur Woodcraft Guild",
            "craft_type": "Woodwork & Carving",
            "scheme_id": "PM-VISH-UP-0412",
            "bio": "Specialist in fine Jali openwork and brass-inlaid Sheesham wood artifacts.",
            "gi_tag": "GI-TAG-UP-05 (Saharanpur Wood Craft)",
            "experience_years": 19,
            "total_sales": 62100.0,
            "active_listings": 15,
            "pending_orders": 5,
            "total_earnings": 43500.0
        }
    ]

    for a in artisans_data:
        artisan = Artisan(**a)
        db.add(artisan)
    db.commit()

    products_data = [
        {
            "id": "kk_prod_001",
            "artisan_id": "artisan_rukmini",
            "title_en": "Handpainted Blue Pottery Plate",
            "title_hi": "हस्तनिर्मित जयपुर ब्लू पॉटरी थाली",
            "craft_type": "Pottery & Ceramics",
            "material": "Quartz Stone & Glass Glaze",
            "location": "Jaipur, Rajasthan",
            "production_time": "3-4 days",
            "story_en": "Blue pottery has been a symbol of Jaipur's rich artistic heritage for centuries. Handcrafted using cobalt and natural quartz.",
            "story_hi": "जयपुर की प्रसिद्ध ब्लू पॉटरी कला में निर्मित थाली, प्राकृतिक क्वार्ट्ज पत्थर और कोबाल्ट रंगों से हस्तनिर्मित।",
            "dimensions": "Dia: 10 in • Height: 1.5 in",
            "weight": "650 grams",
            "tags": "Handmade,GI Tag,Eco-friendly,Traditional,Featured",
            "rating": 4.9,
            "reviews_count": 48,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
            "material_cost": 400.0,
            "labor_hours": 8.0,
            "labor_wage": 800.0,
            "cost_floor": 1250.0,
            "retail": 1250.0,
            "wholesale": 950.0,
            "margin": 42.0,
            "explanation": "Guarantees Rs 800 skilled artisan living wage + Rs 400 materials + packaging."
        },
        {
            "id": "kk_prod_002",
            "artisan_id": "artisan_meera",
            "title_en": "Handcrafted Terracotta Decorative Vase",
            "title_hi": "पारंपरिक खुरजा मिट्टी का कलात्मक फूलदान",
            "craft_type": "Pottery & Ceramics",
            "material": "Natural Terracotta Clay",
            "location": "Khurja, Uttar Pradesh",
            "production_time": "2-3 days",
            "story_en": "Wheel-thrown by Kumhar community artisans using purified alluvial clay, kiln-fired in slow wood flames.",
            "story_hi": "गंगा के शुद्ध दोमट मिट्टी से चाक पर गढ़ा गया फूलदान, लकड़ी की धीमी आंच में पकाया हुआ।",
            "dimensions": "Height: 12 in • Base: 5 in",
            "weight": "950 grams",
            "tags": "Organic,Terracotta,Wheel-Thrown,GI Tag",
            "rating": 4.8,
            "reviews_count": 32,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=800&auto=format&fit=crop&q=80",
            "material_cost": 350.0,
            "labor_hours": 6.0,
            "labor_wage": 600.0,
            "cost_floor": 1000.0,
            "retail": 1200.0,
            "wholesale": 920.0,
            "margin": 38.0,
            "explanation": "Guarantees Rs 600 artisan wage + Rs 350 natural clay & firing."
        },
        {
            "id": "kk_prod_003",
            "artisan_id": "artisan_ramprasad",
            "title_en": "Handwoven Banarasi Katan Silk Dupatta",
            "title_hi": "शुद्ध बनारसी कतान सिल्क ज़री दुपट्टा",
            "craft_type": "Textiles & Weaving",
            "material": "Pure Mulberry Silk & Gold Zari",
            "location": "Varanasi, Uttar Pradesh",
            "production_time": "12-14 days",
            "story_en": "Handloom woven in Varanasi with pure Mulberry silk and fine gold zari warp, featuring traditional paisley motifs.",
            "story_hi": "वाराणसी के हथकरघे पर सोने की जरी से बुना गया शुद्ध कतान सिल्क दुपट्टा।",
            "dimensions": "Length: 2.5 m • Width: 36 in",
            "weight": "320 grams",
            "tags": "Handloom,Silk Mark,Gold Zari,Varanasi Heritage",
            "rating": 5.0,
            "reviews_count": 64,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80",
            "material_cost": 1100.0,
            "labor_hours": 16.0,
            "labor_wage": 1600.0,
            "cost_floor": 2750.0,
            "retail": 2800.0,
            "wholesale": 2100.0,
            "margin": 45.0,
            "explanation": "Guarantees Rs 1600 master weaver wage (16 hrs) + Rs 1100 silk & zari."
        },
        {
            "id": "kk_prod_004",
            "artisan_id": "artisan_aslam",
            "title_en": "Royal Moradabad Hand-Chiseled Brass Diya Set",
            "title_hi": "मुरादाबाद हस्त-नक्काशीदार पीतल दीया सेट",
            "craft_type": "Metalwork & Brass",
            "material": "Heavy Cast Brass",
            "location": "Moradabad, Uttar Pradesh",
            "production_time": "4-5 days",
            "story_en": "Handcrafted by hereditary brassmiths of the Brass City using sand-casting and delicate hand-engraving.",
            "story_hi": "पीतल नगरी मुरादाबाद के कारीगरों द्वारा नक्काशीदार शुद्ध पीतल दीया सेट।",
            "dimensions": "Height: 6 in • Width: 4 in",
            "weight": "850 grams",
            "tags": "Brass,Festive,Hand-Chiseled,Moradabad Craft",
            "rating": 4.9,
            "reviews_count": 28,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?w=800&auto=format&fit=crop&q=80",
            "material_cost": 550.0,
            "labor_hours": 10.0,
            "labor_wage": 1000.0,
            "cost_floor": 1600.0,
            "retail": 1650.0,
            "wholesale": 1280.0,
            "margin": 40.0,
            "explanation": "Guarantees Rs 1000 brass artisan wage + Rs 550 virgin brass alloy."
        },
        {
            "id": "kk_prod_005",
            "artisan_id": "artisan_shanti",
            "title_en": "Traditional Madhubani Peacock Wall Art",
            "title_hi": "पारंपरिक मिथिला मधुबनी मयूर चित्रकला",
            "craft_type": "Paintings & Art",
            "material": "Handmade Lokta Paper & Plant Dyes",
            "location": "Madhubani, Bihar",
            "production_time": "6-8 days",
            "story_en": "Authentic Kachni style Madhubani painting portraying dancing peacocks, created using bamboo twigs and plant pigments.",
            "story_hi": "बांस की तीली और प्राकृतिक वानस्पतिक रंगों से निर्मित प्राचीन मिथिला मयूर चित्र।",
            "dimensions": "15 in x 22 in (Unframed)",
            "weight": "180 grams",
            "tags": "Folk Art,Madhubani,GI Tag,Natural Dyes",
            "rating": 5.0,
            "reviews_count": 52,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80",
            "material_cost": 600.0,
            "labor_hours": 20.0,
            "labor_wage": 2000.0,
            "cost_floor": 2650.0,
            "retail": 3200.0,
            "wholesale": 2400.0,
            "margin": 48.0,
            "explanation": "Guarantees Rs 2000 skilled folk artist fee (20 hrs) + natural pigments."
        },
        {
            "id": "kk_prod_006",
            "artisan_id": "artisan_imran",
            "title_en": "Hand-Carved Saharanpur Teakwood Box",
            "title_hi": "सहारनपुर नक्काशीदार सागौन की लकड़ी का बक्सा",
            "craft_type": "Woodwork & Carving",
            "material": "Seasoned Teak Wood & Brass Inlay",
            "location": "Saharanpur, Uttar Pradesh",
            "production_time": "5-6 days",
            "story_en": "Delicately carved from single-block seasoned teakwood with brass wire inlay (Tarkashi).",
            "story_hi": "सहारनपुर की प्रसिद्ध तारकशी और नक्काशी से बना सागौन का आभूषण बक्सा।",
            "dimensions": "8 x 5 x 4 in",
            "weight": "750 grams",
            "tags": "Teak Wood,Jali Carving,Brass Inlay,Handmade",
            "rating": 4.8,
            "reviews_count": 39,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80",
            "material_cost": 500.0,
            "labor_hours": 12.0,
            "labor_wage": 1200.0,
            "cost_floor": 1750.0,
            "retail": 1800.0,
            "wholesale": 1350.0,
            "margin": 41.0,
            "explanation": "Guarantees Rs 1200 woodcraft master wage + Rs 500 seasoned wood."
        },
        {
            "id": "kk_prod_007",
            "artisan_id": "artisan_rukmini",
            "title_en": "Hand-Embroidered Kutch Mirror-Work Cushion",
            "title_hi": "कच्छ हाथ की कढ़ाई व शीशा वर्क कुशन कवर",
            "craft_type": "Textiles & Weaving",
            "material": "Organic Cotton & Abhala Mirrors",
            "location": "Kutch, Gujarat",
            "production_time": "3-4 days",
            "story_en": "Crafted by pastoral artisan women in Bhuj utilizing Kutchi Ahir needlework and hand-cut glass mirrors.",
            "story_hi": "गुजरात के कच्छ क्षेत्र की ग्रामीण महिलाओं द्वारा तैयार पारंपरिक कशीदाकारी कुशन।",
            "dimensions": "16 x 16 in",
            "weight": "240 grams",
            "tags": "Mirror Work,Kutch Embroidery,Cotton,Fair Trade",
            "rating": 4.9,
            "reviews_count": 41,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?w=800&auto=format&fit=crop&q=80",
            "material_cost": 320.0,
            "labor_hours": 7.0,
            "labor_wage": 700.0,
            "cost_floor": 1070.0,
            "retail": 1100.0,
            "wholesale": 850.0,
            "margin": 39.0,
            "explanation": "Guarantees Rs 700 tribal woman living wage + Rs 320 cotton fabric & mirrors."
        },
        {
            "id": "kk_prod_008",
            "artisan_id": "artisan_aslam",
            "title_en": "Ancient Lost-Wax Bastar Dokra Nandi Figurine",
            "title_hi": "प्राचीन बस्तर ढोकरा नंदी बैल मूर्ति",
            "craft_type": "Metalwork & Brass",
            "material": "Bell Metal & Recycled Brass",
            "location": "Bastar, Chhattisgarh",
            "production_time": "5-6 days",
            "story_en": "Sculpted by Ghadwa tribal artisans of Bastar using the 4000-year-old lost-wax process.",
            "story_hi": "बस्तर की 4000 वर्ष पुरानी ढोकरा पद्धति से निर्मित आदिवासी नंदी बैल शिल्प।",
            "dimensions": "7 x 4 x 5 in",
            "weight": "900 grams",
            "tags": "Dokra,Lost-Wax,Tribal Craft,GI Tag",
            "rating": 5.0,
            "reviews_count": 36,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80",
            "material_cost": 480.0,
            "labor_hours": 9.0,
            "labor_wage": 900.0,
            "cost_floor": 1430.0,
            "retail": 1450.0,
            "wholesale": 1120.0,
            "margin": 43.0,
            "explanation": "Guarantees Rs 900 tribal artisan wage + Rs 480 bronze alloy."
        },
        {
            "id": "kk_prod_009",
            "artisan_id": "artisan_rukmini",
            "title_en": "Handwoven Assam Golden Bamboo Tea Tray",
            "title_hi": "असम प्राकृतिक सुनहरा बांस हस्तनिर्मित टी-ट्रे",
            "craft_type": "Bamboo & Natural Fibres",
            "material": "Muli Bamboo & Natural Cane",
            "location": "Barpeta, Assam",
            "production_time": "3-4 days",
            "story_en": "Woven from treated Assam Muli bamboo using centuries-old tight diagonal twill weave, sealed with natural non-toxic lacquer.",
            "story_hi": "असम के पारंपरिक बांस शिल्पकारों द्वारा बुनी गई टिकाऊ और पर्यावरण-अनुकूल टी-ट्रे।",
            "dimensions": "14 x 10 x 2 in",
            "weight": "380 grams",
            "tags": "Bamboo,Eco-friendly,Assam Craft,Sustainable",
            "rating": 4.9,
            "reviews_count": 29,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1595231776515-ddffb1f4eb73?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1595231776515-ddffb1f4eb73?w=800&auto=format&fit=crop&q=80",
            "material_cost": 220.0,
            "labor_hours": 6.0,
            "labor_wage": 600.0,
            "cost_floor": 850.0,
            "retail": 890.0,
            "wholesale": 680.0,
            "margin": 36.0,
            "explanation": "Guarantees Rs 600 artisan wage + Rs 220 seasoned bamboo & cane."
        },
        {
            "id": "kk_prod_010",
            "artisan_id": "artisan_imran",
            "title_en": "Channapatna Non-Toxic Lacquerware Wooden Stacker",
            "title_hi": "चन्नापटना प्राकृतिक रंगीन लकड़ी का खिलौना स्टैकर",
            "craft_type": "Woodwork & Carving",
            "material": "Ivory Wood (Wrightia Tinctoria) & Natural Lac Dyes",
            "location": "Channapatna, Karnataka",
            "production_time": "2-3 days",
            "story_en": "Turned on traditional wood lathes and buffed with natural vegetable-dyed lac (turmeric, indigo). 100% child-safe and GI Tag certified.",
            "story_hi": "कर्नाटक के चन्नापटना का प्रसिद्ध बाल-सुरक्षित प्राकृतिक रंगों वाला लकड़ी का स्टैकर।",
            "dimensions": "Height: 8 in • Dia: 4 in",
            "weight": "420 grams",
            "tags": "Channapatna,Wooden Toys,GI Tag,Child Safe",
            "rating": 5.0,
            "reviews_count": 58,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&auto=format&fit=crop&q=80",
            "material_cost": 260.0,
            "labor_hours": 5.0,
            "labor_wage": 500.0,
            "cost_floor": 780.0,
            "retail": 820.0,
            "wholesale": 620.0,
            "margin": 35.0,
            "explanation": "Guarantees Rs 500 artisan wage + Rs 260 safe wood & vegetable lac dyes."
        },
        {
            "id": "kk_prod_011",
            "artisan_id": "artisan_ramprasad",
            "title_en": "Kashmiri Handwoven Pure Pashmina Cashmere Shawl",
            "title_hi": "शुद्ध कश्मीरी हस्तनिर्मित पश्मीना शॉल",
            "craft_type": "Textiles & Weaving",
            "material": "100% Changthangi Mountain Goat Cashmere",
            "location": "Srinagar, Jammu & Kashmir",
            "production_time": "25-30 days",
            "story_en": "Hand-spun on traditional Yender charkhas and woven on handlooms by master Kashmiri weavers. Soft, featherlight warmth with Sozni needlework.",
            "story_hi": "चांगथांगी पश्मीना बकरी के महीन ऊन से हाथ से कता और बुना गया अत्यंत कोमल व गर्म शॉल।",
            "dimensions": "200 cm x 100 cm",
            "weight": "190 grams",
            "tags": "Pashmina,GI Tag,Cashmere,Kashmir Heritage,Luxury",
            "rating": 5.0,
            "reviews_count": 72,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80",
            "material_cost": 2800.0,
            "labor_hours": 35.0,
            "labor_wage": 3500.0,
            "cost_floor": 6500.0,
            "retail": 6800.0,
            "wholesale": 5200.0,
            "margin": 45.0,
            "explanation": "Guarantees Rs 3500 master Kashmiri spinner/weaver wage + Rs 2800 pure Pashmina fleece."
        },
        {
            "id": "kk_prod_012",
            "artisan_id": "artisan_shanti",
            "title_en": "Kutch Traditional Rogan Art Floral Wall Hanging",
            "title_hi": "कच्छ की दुर्लभ रोगन कला हस्तनिर्मित दीवार चित्र",
            "craft_type": "Paintings & Art",
            "material": "Castor Oil Paste & Natural Mineral Pigments on Silk",
            "location": "Nirona, Kutch, Gujarat",
            "production_time": "10-12 days",
            "story_en": "Practiced by only a few surviving families in Nirona. Boiled castor oil paste mixed with pigments is hand-stretched with a metal stylus to form intricate floral symmetry.",
            "story_hi": "गुजरात के निरोना गाँव की 400 साल पुरानी दुर्लभ रोगन कला, अरण्डी के तेल और धातु की सलाई से निर्मित।",
            "dimensions": "18 x 24 in",
            "weight": "210 grams",
            "tags": "Rogan Art,Rare Heritage,GI Tag,Gujarat,Collector Piece",
            "rating": 5.0,
            "reviews_count": 44,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&auto=format&fit=crop&q=80",
            "material_cost": 900.0,
            "labor_hours": 24.0,
            "labor_wage": 2400.0,
            "cost_floor": 3400.0,
            "retail": 3600.0,
            "wholesale": 2800.0,
            "margin": 46.0,
            "explanation": "Guarantees Rs 2400 rare master artisan fee (24 hrs) + boiled castor oil & mineral colors."
        },
        {
            "id": "kk_prod_013",
            "artisan_id": "artisan_aslam",
            "title_en": "Jaipur Kundan Meenakari Floral Choker & Earrings",
            "title_hi": "जयपुर कुंदन मीनाकारी हस्तनिर्मित चोकर व झुमकी सेट",
            "craft_type": "Handmade Jewellery",
            "material": "Brass Base, 24K Gold Foil, Glass Kundan & Enamel",
            "location": "Jaipur, Rajasthan",
            "production_time": "7-9 days",
            "story_en": "Traditional Rajasthani Kundan Jadau work with vivid red and green Meenakari enameling on the reverse side. Strung with semi-precious pearls.",
            "story_hi": "शाही राजस्थानी कुंदन जड़ाई और पीछे की तरफ बारीक मीनाकारी से सुसज्जित आभूषण सेट।",
            "dimensions": "Choker: 14 in adjustable • Earrings: 2.5 in",
            "weight": "120 grams",
            "tags": "Kundan,Meenakari,Royal Heritage,Jewellery,Handmade",
            "rating": 4.9,
            "reviews_count": 51,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&auto=format&fit=crop&q=80",
            "material_cost": 850.0,
            "labor_hours": 14.0,
            "labor_wage": 1400.0,
            "cost_floor": 2350.0,
            "retail": 2450.0,
            "wholesale": 1900.0,
            "margin": 44.0,
            "explanation": "Guarantees Rs 1400 skilled jadau goldsmith wage + Rs 850 raw pearls, stones & enamel."
        },
        {
            "id": "kk_prod_014",
            "artisan_id": "artisan_aslam",
            "title_en": "Bidriware Pure Silver Inlaid Zinc Floral Flask",
            "title_hi": "कर्नाटक बिदरीवेयर शुद्ध चांदी की नक्काशीदार सुराही",
            "craft_type": "Metalwork & Brass",
            "material": "Zinc-Copper Alloy & 99.9% Pure Silver Inlay",
            "location": "Bidar, Karnataka",
            "production_time": "8-10 days",
            "story_en": "Century-old Persian technique where pure silver wire is hand-hammered into engraved zinc alloy and blackened with historic Bidar fort soil.",
            "story_hi": "बीदर के किले की विशेष मिट्टी से काला रंग और शुद्ध चांदी की महीन तारकशी से अलंकृत सुराही।",
            "dimensions": "Height: 9 in • Base: 3.5 in",
            "weight": "680 grams",
            "tags": "Bidriware,Silver Inlay,GI Tag,Karnataka Heritage",
            "rating": 5.0,
            "reviews_count": 33,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80",
            "material_cost": 950.0,
            "labor_hours": 18.0,
            "labor_wage": 1800.0,
            "cost_floor": 2850.0,
            "retail": 2950.0,
            "wholesale": 2300.0,
            "margin": 42.0,
            "explanation": "Guarantees Rs 1800 master Bidri artisan living wage + Rs 950 pure silver wire & zinc alloy."
        },
        {
            "id": "kk_prod_015",
            "artisan_id": "artisan_shanti",
            "title_en": "Tanjore 22K Gold Foil Embossed Temple Painting",
            "title_hi": "तंजौर 22-कैरेट स्वर्ण पत्र उभरा हुआ मंदिर चित्र",
            "craft_type": "Paintings & Art",
            "material": "Teak Wood Board, 22K Gold Foil & Jaipur Gemstones",
            "location": "Thanjavur, Tamil Nadu",
            "production_time": "14-18 days",
            "story_en": "Classical South Indian painting crafted with Gesso relief work, adorned with pure 22-carat gold leaves and semi-precious stones.",
            "story_hi": "तमिलनाडु की प्राचीन तंजावुर शैली में 22K सोने के वर्क और रत्नों से सुसज्जित पवित्र चित्रकला।",
            "dimensions": "16 x 12 in (With Teak Frame)",
            "weight": "1.4 kg",
            "tags": "Tanjore Painting,22K Gold,GI Tag,South Indian Heritage",
            "rating": 5.0,
            "reviews_count": 47,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&auto=format&fit=crop&q=80",
            "material_cost": 1800.0,
            "labor_hours": 26.0,
            "labor_wage": 2600.0,
            "cost_floor": 4500.0,
            "retail": 4800.0,
            "wholesale": 3700.0,
            "margin": 46.0,
            "explanation": "Guarantees Rs 2600 temple artist fee (26 hrs) + Rs 1800 22K gold foil & teak frame."
        },
        {
            "id": "kk_prod_016",
            "artisan_id": "artisan_meera",
            "title_en": "Khurja Hand-Glazed Ceramic Indoor Planter",
            "title_hi": "खुरजा हस्त-चमकदार सिरेमिक इनडोर गमला",
            "craft_type": "Pottery & Ceramics",
            "material": "Stoneware Clay & Lead-Free Glaze",
            "location": "Khurja, Uttar Pradesh",
            "production_time": "3-4 days",
            "story_en": "High-temperature fired stoneware planter with subtle crackle glaze, perfect for modern living spaces and heritage homes.",
            "story_hi": "उच्च तापमान पर पकाया गया पर्यावरण-अनुकूल खुरजा सिरेमिक गमला, इनडोर पौधों के लिए आदर्श।",
            "dimensions": "Height: 7 in • Dia: 6.5 in",
            "weight": "800 grams",
            "tags": "Stoneware,Ceramics,Khurja,Planter,Eco-friendly",
            "rating": 4.8,
            "reviews_count": 35,
            "is_trending": True,
            "raw_img": "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&auto=format&fit=crop&q=80",
            "studio_img": "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&auto=format&fit=crop&q=80",
            "material_cost": 280.0,
            "labor_hours": 5.0,
            "labor_wage": 500.0,
            "cost_floor": 800.0,
            "retail": 850.0,
            "wholesale": 650.0,
            "margin": 37.0,
            "explanation": "Guarantees Rs 500 ceramicist living wage + Rs 280 raw stoneware clay & glazes."
        }
    ]

    for p in products_data:
        product = Product(
            id=p["id"],
            artisan_id=p["artisan_id"],
            title_en=p["title_en"],
            title_hi=p["title_hi"],
            craft_type=p["craft_type"],
            material=p["material"],
            location=p["location"],
            production_time=p["production_time"],
            story_en=p["story_en"],
            story_hi=p["story_hi"],
            dimensions=p["dimensions"],
            weight=p["weight"],
            tags=p["tags"],
            rating=p["rating"],
            reviews_count=p["reviews_count"],
            is_trending=p["is_trending"],
            status="PUBLISHED"
        )
        db.add(product)

        media = ProductMedia(
            id=f"media_{p['id']}",
            product_id=p["id"],
            original_url=p["raw_img"],
            enhanced_studio_url=p["studio_img"],
            thumbnail_url=p["studio_img"]
        )
        db.add(media)

        pricing = ProductPricing(
            id=f"pricing_{p['id']}",
            product_id=p["id"],
            material_cost=p["material_cost"],
            labor_hours=p["labor_hours"],
            guaranteed_labor_wage=p["labor_wage"],
            cost_floor=p["cost_floor"],
            recommended_retail_price=p["retail"],
            wholesale_b2b_price=p["wholesale"],
            profit_margin_pct=p["margin"],
            model_version="RandomForest-v1.0 (300 estimators)",
            explanation=p["explanation"]
        )
        db.add(pricing)
    db.commit()

    # Seed Orders
    orders_data = [
        {
            "id": "OD_ONDC_83921",
            "product_id": "kk_prod_001",
            "product_title": "Handpainted Blue Pottery Plate",
            "buyer_name": "Aman Verma",
            "delivery_city": "New Delhi, Delhi",
            "quantity": 1,
            "unit_price": 1250.0,
            "total_amount": 1250.0,
            "buyer_app": "Paytm ONDC Store",
            "payment_status": "SETTLED_VIA_UPI",
            "order_status": "Shipped",
            "tracking_id": "DELHIVERY_DL9021",
            "artisan_id": "artisan_rukmini",
            "created_at": datetime.utcnow() - timedelta(hours=4)
        },
        {
            "id": "OD_ONDC_83922",
            "product_id": "kk_prod_002",
            "product_title": "Terracotta Decorative Vase",
            "buyer_name": "Diya Sen",
            "delivery_city": "Mumbai, Maharashtra",
            "quantity": 2,
            "unit_price": 1200.0,
            "total_amount": 2400.0,
            "buyer_app": "Magicpin ONDC",
            "payment_status": "SETTLED_VIA_UPI",
            "order_status": "Processing",
            "tracking_id": "SHADOWFAX_MH4102",
            "artisan_id": "artisan_meera",
            "created_at": datetime.utcnow() - timedelta(hours=12)
        },
        {
            "id": "OD_ONDC_83923",
            "product_id": "kk_prod_006",
            "product_title": "Hand-Carved Teakwood Box",
            "buyer_name": "Rohan Gupta",
            "delivery_city": "Bengaluru, Karnataka",
            "quantity": 1,
            "unit_price": 1800.0,
            "total_amount": 1800.0,
            "buyer_app": "Mystore ONDC",
            "payment_status": "SETTLED_VIA_UPI",
            "order_status": "Confirmed",
            "tracking_id": "BLUEDART_BL5821",
            "artisan_id": "artisan_imran",
            "created_at": datetime.utcnow() - timedelta(hours=22)
        },
        {
            "id": "OD_ONDC_83924",
            "product_id": "kk_prod_011",
            "product_title": "Kashmiri Pure Pashmina Shawl",
            "buyer_name": "Kavita Rao",
            "delivery_city": "Hyderabad, Telangana",
            "quantity": 1,
            "unit_price": 6800.0,
            "total_amount": 6800.0,
            "buyer_app": "Pincode by PhonePe",
            "payment_status": "SETTLED_VIA_UPI",
            "order_status": "Processing",
            "tracking_id": "DELHIVERY_HY8831",
            "artisan_id": "artisan_ramprasad",
            "created_at": datetime.utcnow() - timedelta(hours=36)
        },
        {
            "id": "OD_ONDC_83925",
            "product_id": "kk_prod_010",
            "product_title": "Channapatna Wooden Stacker",
            "buyer_name": "Siddharth Nair",
            "delivery_city": "Kochi, Kerala",
            "quantity": 2,
            "unit_price": 820.0,
            "total_amount": 1640.0,
            "buyer_app": "Paytm ONDC Store",
            "payment_status": "SETTLED_VIA_UPI",
            "order_status": "Shipped",
            "tracking_id": "EKART_KC1920",
            "artisan_id": "artisan_imran",
            "created_at": datetime.utcnow() - timedelta(hours=48)
        }
    ]

    for o in orders_data:
        order = Order(**o)
        db.add(order)
    db.commit()
    db.close()
    print("Database seeding completed successfully with 16 master products!")
